---
- name: Configure Vagrant VMs
  hosts: all
  connection: ssh
  any_errors_fatal: true
  become: true
  tasks:
    - name: stop and disable iptables service
      service:
        name: iptables
        state: stopped
        enabled: no

    - name: Set default ipv4 fact
      set_fact:
        ansible_default_ipv4: "{{ ansible_eth1.ipv4 }}"

    - name: Install Postgres RPM
      yum:
        name: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-centos95-9.5-2.noarch.rpm
        state: present

    - name: Install python psycopg2
      yum: name=python-psycopg2 state=present
