---
#role: barman

- name: Install Postgres 9.4 Repo
  yum: name={{ pg_rpm[pg_version].url }} state=present

- name: Install pg client and barman
  yum: name={{ item }} state=present
  with_items:
    - postgresql{{ pg_version |replace(".","") }}
    - barman-{{ barman_version }}

- name: Create directory structure
  file: path={{ item }} state=directory
  with_items:
    - /etc/barman
    - /etc/barman.d

- name: Remove default barman.conf if it exists
  file: path=/etc/barman.conf state=absent

- name: Template barman.conf
  template:
    src: barman_conf.j2
    dest: /etc/barman/barman.conf
    owner: barman
    group: barman

- name: Template /etc/barman.d/ config files for all postgres hosts
  template:
    src: host_conf.j2
    dest: /etc/barman.d/pg-{{ hostvars[item].pg_cluster }}.conf
    owner: barman
    group: barman
  with_items:
    - "{{ groups[pg_group] }}"
  when: "'{{ pg_slave_group }}' not in hostvars[item].group_names"

- name: Cron Weekly Full Backup (Saturday)
  cron:
    name: Weekly Full Backup Sat 10pm
    minute: 00
    hour: 22
    weekday: 6
    job: barman -q backup all
    user: barman

- name: Cron Daily Incremental Backup
  cron:
    name: Daily Incremental Backup 10pm
    minute: 00
    hour: 22
    weekday: 0-5
    job: barman -q backup --reuse-backup link all
    user: barman

- name: Create Barman SSH Key and Set Password
  user:
    name: barman
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_comment: "barman@{{ ansible_hostname }}"
    ssh_key_file: .ssh/id_rsa
  register: barman_key

- name: set barman key host fact
  set_fact:
    barman_key: "{{ barman_key.ssh_public_key }}"

- name: Set file permissions on ssh key
  file: path=/var/lib/barman/.ssh/id_rsa mode=0600

- name: Add barman to Sudoers file
  lineinfile: 'dest=/etc/sudoers state=present regexp="^barman ALL\=" line="barman ALL=(ALL) NOPASSWD: ALL"'
