Vagrant.configure("2") do |config|
  config.vm.box = "nrel/CentOS-6.6-x86_64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/pg-config.yml"
    ansible.galaxy_role_file = "provisioning/requirements.yml"
    ansible.limit = 'all'
    ansible.groups = {
      "postgres" => ["pg-a-1", "pg-a-2", "pg-b-1", "pg-b-2"],
      "cluster_a" => ["pg-a-1", "pg-a-2"],
      "cluster_b" => ["pg-b-1", "pg-b-2"],
      "master" => ["pg-a-1", "pg-b-1"],
      "standby" => ["pg-a-2", "pg-b-2"],
      "barman" => ["barman"],
      "pgbouncer" => ["pgbouncer"]
    }

  end

  config.vm.define "pg-a-1" do |node|
    node.vm.hostname = "pg-a-1"
    node.vm.network :private_network, ip: "192.168.50.10"
    node.vm.network :forwarded_port, guest: "5432", host: "7001" # postgres
  end

  config.vm.define "pg-a-2" do |node|
    node.vm.hostname = "pg-a-2"
    node.vm.network :private_network, ip: "192.168.50.11"
    node.vm.network :forwarded_port, guest: "5432", host: "7002" # postgres
  end

  config.vm.define "pg-b-1" do |node|
    node.vm.hostname = "pg-b-1"
    node.vm.network :private_network, ip: "192.168.50.12"
    node.vm.network :forwarded_port, guest: "5432", host: "7003" # postgres
  end

  config.vm.define "pg-b-2" do |node|
    node.vm.hostname = "pg-b-2"
    node.vm.network :private_network, ip: "192.168.50.13"
    node.vm.network :forwarded_port, guest: "5432", host: "7004" # postgres
  end

  config.vm.define "barman" do |node|
    node.vm.hostname = "barman"
    node.vm.network :private_network, ip: "192.168.50.41"
  end

  config.vm.define "pgbouncer" do |node|
    node.vm.hostname = "pgbouncer"
    node.vm.network :private_network, ip: "192.168.50.31"
    node.vm.network :forwarded_port, guest: "6432", host: "8001"
  end

end
