---
# Update postgresql.conf and pg_hba.conf for standard postgres installation
# This will restart postgres only if changes are made that require restart

- name: configure_postgres | Update postgresql.conf - reload after any changes
  lineinfile:
    dest: "{{ pgdata_dir }}/postgresql.conf"
    state: present
    line: "{{ item.value }}"
    regexp: "{{ item.regexp }}"
  with_items: "{{ postgresql_conf[pg_version] }}"
  notify:
    - reload postgres
  tags: postgres_conf
  when: "'{{ pg_standby_group }}' not in group_names and '{{ barman_group }}' not in group_names"

- name: configure_postgres | Update postgresql.conf - changes require restart
  lineinfile:
    dest: "{{ pgdata_dir }}/postgresql.conf"
    state: present
    line: "{{ item.value }}"
    regexp: "{{ item.regexp }}"
  with_items: "{{ postgresql_conf_restart }}"
  notify:
    - restart postgres
  tags: postgres_conf
  when: "'{{ pg_standby_group }}' not in group_names and '{{ barman_group }}' not in group_names"

- name: configure_postgres | Update pg_hba.conf
  lineinfile: dest="{{ pgdata_dir }}/pg_hba.conf" state=present line="{{ item.value }}" regexp="{{ item.regexp }}"
  with_items: "{{ pg_hba_conf }}"
  notify:
    - reload postgres
  tags: pg_hba_conf
  when: "'{{ pg_standby_group }}' not in group_names and '{{ barman_group }}' not in group_names"

# Run any handlers that have been notified
- name: configure_postgres | Flush Handlers
  meta: flush_handlers

- name: configure_postgres | Create log directory
  file:
    path: /var/lib/pgsql/logs
    state: directory
    owner: postgres
    group: postgres

- name: configure_postgres | Add cronjob for cleaning up script logs
  cron:
    name: "cleanup logfiles older than 4 weeks"
    minute: 0
    hour: 0
    job: "find /var/lib/pgsql/logs/* -mtime +28 |xargs rm"
    user: postgres

- name: configure_postgres | Add cronjob for removing old log files
  cron:
    name: "cleanup pg log files older than 2 weeks"
    minute: 0
    hour: 0
    job: "find /var/lib/pgsql/{{ pg_version }}/data/pg_log/* -mtime +14 |xargs rm"
    user: postgres

- name: configure_postgres | Add cronjob for removing old pg_dump files
  cron:
    name: "cleanup dumps older than 3 days"
    minute: 0
    hour: 0
    job: "find /var/lib/pgsql/{{ pg_version }}/backups/* -mtime +3 |xargs rm"
    user: postgres
