---

# workaround for https://github.com/ansible/ansible-modules-core/issues/1687
- name: install_postgres | Install Postgres RPM
  yum: name={{ pg_rpm[pg_version].url }} state=present

- name: install_postgres | Install Postgres
  yum: name={{ item }} state=present
  with_items:
    - postgresql{{ pg_version |replace(".","") }}-server #replace turns 9.4 to 94
    - postgresql{{ pg_version |replace(".","") }}-contrib
    - postgresql{{ pg_version |replace(".","") }}-devel
    - python-psycopg2 # required for ansible postgresql modules
    - rsync

- name: install_postgres | Check if Postgres Cluster already exists
  stat:
    path: /var/lib/pgsql/{{ pg_version }}/data/postgresql.conf
  register: pg_exists
  tags: cluster_check

- name: install_postgres | Create Postgres Database Cluster
  command: service postgresql-{{ pg_version }} initdb
  when: not pg_exists.stat.exists
  tags: cluster_check

- name: install_postgres | Set owner for data directory
  file: state=directory path="{{ pgdata_dir }}" owner=postgres group=postgres

- name: install_postgres | Enable Postgres Service
  service: name=postgresql-{{ pg_version }} enabled=yes state=started
